df<-read.table(file.choose(),sep=",",header = TRUE)
View(df)
df<-read.table(file.choose(),sep=",",header = TRUE)
str(df)
summary(df)
df=subset(df,select = -OpenInt)
install.packages("tseries")
library(tseries)
library(MASS)
df$Volume<-log(df$Volume)
acf(df,lag.max=20)
pacf(df,lag.max = 20)
summary(df)
adf.test(df$Volume)
adf.test(df$Open)
adf.test(df$High)
adf.test(df$Low)
adf.test(df$Close)
adf.test(df$Volume)
?adf.test
model<-ts(df)
model
str(df)
df$Date<-as.Date(df$Date)
str(df)
model<-ts(df,frequency = 10)
model
install.packages("forecast")
library(forecast)
auto.arima(model)
fitmodel<-auto.arima(model)
str(model)
auto.arima(model[,1])
plot(model[1,2])
plot(model[,1:2])
plot(model[,2:5])
arima_forecast = forecast(fitmodel,h = 10)
fitmodel<-auto.arima(model)
fitmodel<-auto.arima(model[,4])
arima_forecast = forecast(fitmodel,h = 10)
plot(arima_forecast)
fitmodel<-auto.arima(model[,3])
arima_forecast = forecast(fitmodel,h = 10)
plot(arima_forecast)
arima_forecast
arima_forecast$mean
arima_forecast$method
arima_forecast$model
arima_forecast$lower
Box.test(arima_forecast$residuals)
Box.test(arima_forecast$residuals,lag=5)
Box.test(arima_forecast$residuals,lag=10)
Box.test(arima_forecast$residuals,lag=15)
Box.test(arima_forecast$residuals,lag=30)
Box.test(arima_forecast$residuals,lag=5,type="Ljung-Box")
plot(arima_forecast)

